In [11]:
from tensorflow.keras.preprocessing.text import one_hot

In [12]:
#Sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [13]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [14]:
#Define the vocab size
voc_size=10000



In [15]:
#One Hot Representation
one_hot_rep=[one_hot(words,voc_size)for words in sent]


In [16]:
one_hot_rep

[[820, 9049, 8343, 8635],
 [820, 9049, 8343, 8542],
 [820, 1725, 8343, 7223],
 [4153, 9550, 8179, 5862, 6415],
 [4153, 9550, 8179, 5862, 580],
 [3504, 820, 7301, 8343, 8603],
 [1809, 4961, 7019, 5862]]

In [18]:
#Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [19]:
import numpy as np

In [20]:
sent_length=8

In [21]:
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)

In [22]:
embedded_docs

array([[   0,    0,    0,    0,  820, 9049, 8343, 8635],
       [   0,    0,    0,    0,  820, 9049, 8343, 8542],
       [   0,    0,    0,    0,  820, 1725, 8343, 7223],
       [   0,    0,    0, 4153, 9550, 8179, 5862, 6415],
       [   0,    0,    0, 4153, 9550, 8179, 5862,  580],
       [   0,    0,    0, 3504,  820, 7301, 8343, 8603],
       [   0,    0,    0,    0, 1809, 4961, 7019, 5862]], dtype=int32)

In [23]:
#Feature Representation
dim=10


In [24]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))

c:\Users\sathwik\OneDrive\Desktop\Deep Learning\dlenv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [25]:
model.compile('adam','mse')

In [27]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step


array([[[-0.02161198, -0.02019074,  0.01259153,  0.01852566,
         -0.04106716, -0.00801973, -0.01704357,  0.02354845,
          0.02787915,  0.01656971],
        [-0.02161198, -0.02019074,  0.01259153,  0.01852566,
         -0.04106716, -0.00801973, -0.01704357,  0.02354845,
          0.02787915,  0.01656971],
        [-0.02161198, -0.02019074,  0.01259153,  0.01852566,
         -0.04106716, -0.00801973, -0.01704357,  0.02354845,
          0.02787915,  0.01656971],
        [-0.02161198, -0.02019074,  0.01259153,  0.01852566,
         -0.04106716, -0.00801973, -0.01704357,  0.02354845,
          0.02787915,  0.01656971],
        [ 0.00374101, -0.02233263,  0.04831837,  0.02469764,
         -0.02574922, -0.03991247, -0.01748685, -0.04859419,
         -0.04150964, -0.03108046],
        [-0.02346162,  0.01968512,  0.01738702,  0.01945559,
         -0.0206216 ,  0.04413802, -0.02889305,  0.01923999,
          0.00437988,  0.02591716],
        [ 0.04999569,  0.03412998, -0.04870277, -0.0

In [29]:
embedded_docs[0]

array([   0,    0,    0,    0,  820, 9049, 8343, 8635], dtype=int32)